### ISSUE TITLE
Download installer

### ISSUE THREAD

**Issue by angoca** [grange74/docker-db2#2]
There could be an easier way to download the DB2 binaries.

I know the DB2 installer has to be downloaded from IBM (fixpack central) and the URL is not the same. However, the URL for the download works for several days:

https://delivery04.dhe.ibm.com/sdfdl/v2/sar/CM/IM/04yrx/0/Xa.2/Xb.jusyLTSp44S03sPo7dOkuuPNYPGduOKijQCAuicsFTCmcyTaVJLKXWtvJPQ/Xc.CM/IM/04yrx/0/v10.5fp5_linuxx64_server_t.tar.gz/Xd./Xf.LPR.D1vk/Xg.7883730/Xi.habanero/XY.habanero/XZ.grlA6AsFBIuMIQhgkuzeJ9ZAh-s/v10.5fp5_linuxx64_server_t.tar.gz

Also, you can provide the direct URL to generate a new Download URL:

http://www.ibm.com/support/fixcentral/swg/quickorder?parent=ibm%7EInformation%2BManagement&product=ibm/Information+Management/DB2&release=10.5.*&platform=Linux+64-bit,x86_64&function=fixId&fixids=DB2-linuxx64-server_t-10.5.0.5-FP005&includeRequisites=1&includeSupersedes=0&downloadMethod=http&source=fc

I use that in my projects with TravisCI. For example: https://travis-ci.org/angoca/db2unit/jobs/44276823

**Comment by grange74** [comment]
Thanks for taking the time to make this suggestion. I will try to incorporate it over the next week or two.

**Comment by grange74** [comment]
Unfortunately it seems that i can't use fixcentral for DB2 Express-C Edition v10.5. From the IBM site: 
"DB2 fix packs can not be used with the Free version of DB2 Express-C." 

The best i could do is get a URL that works for a short period of time from another part of the IBM site:
https://iwm.dhe.ibm.com/sdfdl/v2/regs2/db2pmopn/db2_v105/expc/Xa.2/Xb.aA_60_-i75OfR94CKScXLUXI9wWeoqJL_cXs54IWwQ/Xc.db2_v105/expc/v10.5_linuxx64_expc.tar.gz/Xd./Xf.LPr.D1vk/Xg.7883149/Xi.swg-db2expressc/XY.regsrvs/XZ.XAjHEg1Vyb6WP_XahQdVZSVCwas/v10.5_linuxx64_expc.tar.gz

The closest i got to getting fixcentral working was using the following link with seems to give version 9.1, though i'm not sure where this is the exact same installer:
http://www-933.ibm.com/support/fixcentral/swg/downloadFixes?parent=ibm~Information%2BManagement&product=ibm/Information+Management/DB2&release=9.1.*&platform=Linux+64-bit,x86_64&function=fixId&fixids=DB2-linuxx64-exp-9.1.0.9-FP009&includeRequisites=1&includeSupersedes=0&downloadMethod=http

**Comment by grange74** [comment]
Updated Dockerfile to download from IBM site as per recommendation.
